name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  ruleset-file-path:
    description: 'Your input description here'
    required: true
    default: 'ruleset.json'
  organization:
    description: 'The organization you are managing the ruleset for. (Default will take the residing org)'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
