name: 'Ruleset as Code'
description:
  'A GitHub Action that helps you manage your GitHub Repository Rulesets as
  code.'
author: 'theztefan'

branding:
  icon: 'clipboard'
  color: 'red'

inputs:
  ruleset-file-path:
    description:
      'The path to the ruleset file that you want to use to update the ruleset.'
    required: true
    default: 'ruleset.json'
  organization:
    description:
      'The organization you are managing the ruleset for. (Default will take the
      residing org)'
    required: false
  token:
    description:
      'GitHub token that is used to get and update the rulesets via the API.'
    required: true

runs:
  using: node20
  main: dist/index.js
